### ISSUE TITLE
New instructions to build GTK theme?

### ISSUE THREAD

**Issue by xfzv** [pwyde/monochrome-kde#4]
With [this commit](https://github.com/KDE/breeze-gtk/commit/58344d6ad8355273b9e4ccda958f54cdaae33c36), the `build_theme.sh` has been replaced with `build_theme.sh.cmake`

As a result, the following from README  no longer works:

```sh
$ cd breeze-gtk/src/
$ sudo sh build_theme.sh -c Monochrome -t /usr/share/themes/Monochrome
```

since `build_theme.sh` no longer exists.

Any chance you could update the instructions?

Thanks.

**Comment by xfzv** [comment]
https://github.com/KDE/breeze-gtk/commit/58344d6ad8355273b9e4ccda958f54cdaae33c36#diff-6aacb436faf8d82956bfe3fe45f16ac9374d337387441cd51d077b122f266274L45

I found a dirty workaround: switching back to `python3` instead of `@PYTHON_EXECUTABLE@` works.

Else, I'm getting:

```sh
build_theme.sh.cmake: line 45: @PYTHON_EXECUTABLE@: command not found
```

**Comment by pwyde** [comment]
Apologies for the extremely late reply. Due to other commitments I have been struggling to find time to update the theme. I have added a pre-build of the GTK2/3/4 theme. See commit a831570d39208789e8682de0c5336f4b4439b1e3.

Also see the updated [README.md](https://github.com/pwyde/monochrome-kde/blob/master/README.md)
